## makeCacheMatrix and cacheSolve create an object-like list and uses functions stored
##in the list to calculate the inverse of a matrix (matrix must be invertable)


## makeCacheMatrix takes an atomic matrix as an argument, and returns a list that stores
## functions to get and set the matrix and its inverse

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setInv <- function(newInv) inv <<- newInv
  getInv <- function() inv
  list(set = set, get = get,
       setInv = setInv,
       getInv = getInv)
}

## cacheSolve takes a list, generated by the makeCacheMatrix function, and checks
## to see if a matrix's inverse has already been calculated and stored. If it has, it returns
## the stored inverse. If not, it calculates and sets the inverse in the cache, and returns it 
## to the console. (matrix must be invertible)

cacheSolve <- function(x, ...) {
  inv <- x$getInv()
  if (!is.null(inv)) {
    message ("getting cached data")
    return (inv)
  }
  mat <- x$get()
  inv <- solve(mat)
  x$setInv(inv)
  inv
}
